version: '3.5'

services:
  media:
    container_name: media-ws
    build: 
      context: .
    image: javeke/image-generator
    working_dir: /usr/app
    env_file: 
     - .env
    tty: true
    ports:
      - "5500:5500"